version: '3.9'

services:
  app:
    image: ghcr.io/glugox/php:8.2-cli
    working_dir: /var/www/html
    volumes:
      - ../laravel-app:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: local
      APP_DEBUG: '1'
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "63790:6379"

volumes:
  mysql-data:
